version: '3.8'

services:
  php:
    build: 
      context: ./docker/php
    container_name: php_symf
    restart: always
    networks:
      - dev
    volumes:
      - ./project:/var/www/
    environment:
      DATABASE_URL: "mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb:3306/${MARIADB_DATABASE}?serverVersion=10.11.6"
      TEST_DATABASE_URL: "mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@mariadb:3306/testbd?serverVersion=10.11.6"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11.6
    container_name: mariadb_symf
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  nginx:
    build: 
      context: ./docker/nginx
    container_name: nginx_symf
    ports:
      - "8090:80"
    volumes:
      - ./project:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_symf
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: